services:
  - type: web
    name: tdlda-api
    runtime: docker
    plan: free
    healthCheckPath: /api/health.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
